automation: !include automations.yaml
breaking_changes:
frontend:
logger:
  default: info
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/ha-floorplan/floorplan.js
      type: module
scene: !include scenes.yaml
script: !include scripts.yaml
weather:
  - platform: darksky
    api_key: !secret darksky_api